### Get all holdings
GET https://stockmarket-backend-fqvv.onrender.com/api/holdings
Accept: application/json

### Buy stocks
POST https://stockmarket-backend-fqvv.onrender.com/api/trade
Content-Type: application/json

{
    "symbol": "AAPL",
    "quantity": 10,
    "type": "buy"
}

### 

POST https://stockmarket-backend-fqvv.onrender.com/api/trade
Content-Type: application/json

{
    "symbol": "GOOGLE",
    "quantity": 20,
    "type": "buy"
}

### Sell stocks
POST https://stockmarket-backend-fqvv.onrender.com/api/trade
Content-Type: application/json

{
    "symbol": "AAPL",
    "quantity": 5,
    "type": "sell"
}

### Sell more shares than available
POST https://stockmarket-backend-fqvv.onrender.com/api/trade
Content-Type: application/json

{
    "symbol": "AAPL",
    "quantity": 20,
    "type": "sell"
}
